# Generated by Django 4.1.7 on 2023-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='media_posters')),
                ('mediayear', models.IntegerField()),
                ('mediatype', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
