# Generated by Django 4.1.7 on 2023-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_media_delete_movie_delete_tvshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
