# Generated by Django 4.1.7 on 2023-06-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_rename_mediaitem_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.CharField(max_length=9),
        ),
    ]
