# Generated by Django 4.1.7 on 2023-06-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0008_media_status_completedmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
        migrations.DeleteModel(
            name='CompletedMedia',
        ),
    ]
