# Generated by Django 4.1.7 on 2023-06-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0009_remove_media_status_delete_completedmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotCompletedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylist.media')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylist.media')),
            ],
        ),
    ]
