# Generated by Django 4.1.7 on 2023-06-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0010_notcompletedmedia_completedmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notcompletedmedia',
            name='media',
        ),
        migrations.DeleteModel(
            name='CompletedMedia',
        ),
        migrations.DeleteModel(
            name='NotCompletedMedia',
        ),
    ]
