# Generated by Django 4.1.7 on 2023-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0012_completedmedia_notcompletedmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animetitle', models.CharField(max_length=255)),
                ('animeposter', models.URLField()),
                ('animeyear', models.CharField(max_length=9)),
            ],
        ),
    ]
