# Generated by Django 4.1.7 on 2023-06-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0013_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_anime_title', models.CharField(max_length=255)),
                ('comp_anime_poster', models.URLField()),
                ('comp_anime_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='NotCompletedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notcomp_anime_title', models.CharField(max_length=255)),
                ('notcomp_anime_poster', models.URLField()),
                ('notcomp_anime_year', models.CharField(max_length=9)),
            ],
        ),
    ]
