# Generated by Django 4.1.7 on 2023-07-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0014_completedanime_notcompletedanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='animegenre',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='completedanime',
            name='comp_anime_genre',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='completedmedia',
            name='comp_genre',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='genre',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='notcompletedanime',
            name='notcomp_anime_genre',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='notcompletedmedia',
            name='notcomp_genre',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
