# Generated by Django 4.1.7 on 2023-07-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0015_anime_animegenre_completedanime_comp_anime_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_anime_title', models.CharField(max_length=255)),
                ('priority_anime_poster', models.URLField()),
                ('priority_anime_year', models.CharField(max_length=9)),
                ('priority_anime_genre', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_title', models.CharField(max_length=255)),
                ('priority_poster', models.URLField()),
                ('priority_year', models.CharField(max_length=9)),
                ('priority_genre', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
